<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Nexus.Core\Nexus.Core.csproj" />
    <ProjectReference Include="..\Nexus.Protocol\Nexus.Protocol.csproj" />
    <ProjectReference Include="..\Nexus.State\Nexus.State.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
